[versions]
agp = "8.5.2"
kotlin = "2.0.21"
coreKtx = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.1.4"
benchmark = "1.3.3"
junit = "1.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-runner = { group = "androidx.test", name = "runner", version = "1.6.2" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-benchmark-junit4 = { group = "androidx.benchmark", name = "benchmark-junit4", version = "1.3.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
benchmark = { id = "androidx.benchmark", version.ref = "benchmark" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
