name: Build

on: workflow_dispatch

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 20
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '20'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup Gradle Cache
      uses: gradle/gradle-build-action@v2
      with:
         gradle-home-cache-cleanup: true
    - name: Build with Gradle
      run: ./gradlew --no-daemon bundleRelease assembleRelease
    - name: Upload app bundle
      uses: actions/upload-artifact@v4.4.3
      with:
        name: app-release.aab
        path: app/build/outputs/bundle/release/app-release.aab
    - name: Upload apk
      uses: actions/upload-artifact@v4.4.3
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
    - run: 'echo Build status report=${{ job.status }}'
